version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /.*/
